#!/usr/bin/perl -X
use strict;
use threads;
use warnings;
use Bio::SeqIO;
use File::Copy;
use File::Spec;
use File::Temp 'tempdir';
use Getopt::Long;
use Bio::Phylo::Util::Logger ':levels';

# process command line arguments
my $indir = '.';
my $verbosity = INFO;
my $outfile;
GetOptions(
	'indir=s'   => \$indir,
	'verbose+'  => \$verbosity,	
	'outfile=s' => \$outfile,
);

# instantiate services
Bio::Phylo::Util::Logger->new(
	'-class'    => 'main',
	'-level'    => $verbosity,
);

# default name
if ( not $outfile ) {
	$outfile = "${indir}/profile.aln";
}
INFO "writing to outfile $outfile";

# do the profiles
my @outfiles = glob qq<${indir}/*.aln>;
INFO "profile aligning ".scalar(@outfiles)." files";

# start iterating
copy( $outfiles[0], $outfile );
for my $i ( 1 .. $#outfiles ) {
	my $time = localtime();
	INFO "[$time] profile align step $i (adding $outfiles[$i])";
	my $tmp = $outfile . '.tmp';
	system( "muscle  -maxiters 1 -diags -profile -in1 $outfile -in2 $outfiles[$i] > $tmp" );
	copy( $tmp, $outfile );
	unlink( $tmp );
}