#!/usr/bin/perl
use strict;
use warnings;
use Bio::SeqIO;
use Getopt::Long;
use Bio::Phylo::Util::Logger ':levels';

# Writes sequences greater than --length from infile to outfile
#
# Usage:
# seqfilter -i infile.fasta -o outfile.fasta -l 25000

# process command line arguments
my $verbosity = INFO;
my $infile;
my $outfile;
my $length = 25_000;
GetOptions(
	'infile=s'  => \$infile,
	'outfile=s' => \$outfile,
	'verbose+'  => \$verbosity,
	'length=i'  => \$length,
);

# open file handle or use STDIN
my $in;
if ( $infile ) {
	$in = Bio::SeqIO(
		'-format' => 'fasta',
		'-file'   => $infile,
	);
}
else {
	$in = Bio::SeqIO(
		'-format' => 'fasta',
		'-fh'     => \*STDIN,
	);
}

# open file handle or STDOUT
my $out;
if ( $outfile ) {
	$out = Bio::SeqIO(
		'-format' => 'fasta',
		'-file'   => ">$outfile",
	);
}
else {
	$out = Bio::SeqIO(
		'-format' => 'fasta',
		'-fh'     => \*STDOUT,
	);
}

# start filtering
while( my $seq = $in->next_seq ) {
	if ( length( $seq->seq ) >= $length ) {
		$out->write_seq( $seq );
	}
}

